langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: c2bzwMDvVLELEfbGqfaHfHELY94D/j8BymckKSLt/AGXgmdlJbdOf0zAiI37IBe7FWSaDo8W4h7L4jyHFGDJAzmqHskFQTNOKWkL3f3kMW9AhvOgmSjuaOQLnAZxkjvlm5EWBpMAZDBM4TOZ6cMUiogZPj5teeBnYissoOuKf3T3jw8dfsP899bWnpCTOobvn0JNSAMVqfqiBkxPYFXxLqS0Xa7jUjtRJdQTcMtQTh/K9x4SfnParoKDhfTeNcN95ZykpRD4ZZZUW/TxRWNnygRr0LQgXIKrSrYCHqj0I5AGmQxz3HqK9y9pvqyWtfYy5l42dH1yC1EWYj2u+rnYwKbMlGHKhGA5D0n6MkrdQIqdOTQc8IliJBlYDEfnNqTjoNDhOA40cjndj6C0n23wCbdn086V4ssLsewIAq+7DCpHphMkTawUwew0ICUvd6tStxK6GHDsCAlIpbnldYacgQJb0Db3xuh0SNW/lp1Al/ihhGl989AD/ICMGCfbP/U4Qeff/2cLoUQ3E6T8TaeaqDdh3oyj3Cb/JkIN1lEMYBWofE/s31PDeMSdPmNxusl60QCwmBwcMJdqsgPqRHmXI39vLLxrRqm5lwOZwXx5q1wJEHBlNtCDxDmSFUYI83A1WeBBoobR+wh2/xdUETvQQDbz98aXaRddzlk18ow0oFU=
  app: infinite-basin-07610
  run: rails db:migrate
dd:
  secure: Je83xjwfzgDTQvQGw8BRehHut17PRkEFiTWOZyWz+G4sR5o0lnVBjbw98nOhfIrfqDl8WgU+bf6H41r440b5FabnVi6ogvGwHw28mPDwqHV5b8nAOAC7cxAz8pNp0Urtae6dQ6UJgtrhGiRte5LtGDMlHU2CaGxFxcI1Ooi0OyQqaWVLKPXGSdskQTuEuV6/oWUY3/IaLVSw4J+aW1nym3ut43WNDu6j6Mh8qKCyCbO77GwzKphd5mn19xTfRidST82BGSvWtkq+mTBiHrFvg1Su3MDm8uzyN8Eqrb4uXgmCJfgK5PIU1GHSvaXNEbgJnQINDVWNjhVCiqeAu2qgyGJvhMDDpzvvVXWh/DErLq2DhI8WUUzCDWL3B2xXR8zFSN1P7H1qKTvNh0PzvVT4W9x9zR5yNATVoWsz+JsZkgNTJ0bna5X0uaup75dEEW6LfXi4vzW+zfRzMdDfqrh1z5Lx8MtrB+h1McVQAu+YHeip1LRdMtQkn+xmu7f322XhaA7jRVZHUks7ZjCtssbSiMhKq+NG6z0a2nFSQgEGZ+BXC14rwo2EYz3zUfhasXG0iMeZYA1CoXL2iVH2WYb1WQs0kTUc3oM1UHuB1CHCni5CIewyhWKp9ZwdejypNF6Vga19Hl0JuKwd+ykxulf8Z3hZnEuotfgtz1CBDobtr3Q=
